declare const micromatch: any;
declare const url: any;
declare const a: any;
declare const yargs: any;
declare const hideBin: any;
declare const argv: any;
declare const fs: any;
declare var path: any;
declare const axios: any;
declare function replaceSnippets(fileAsArray: any): Promise<any>;
